# Autogenerated wrapper script for ZXing_CPP_jll for aarch64-apple-darwin
export libZXing

JLLWrappers.@generate_wrapper_header("ZXing_CPP")
JLLWrappers.@declare_library_product(libZXing, "@rpath/libZXing.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libZXing,
        "lib/libZXing.2.3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
